// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASgcpUqHrlqxnPCOcCdDuRhi-6xXMtroA',
    appId: '1:427595722527:web:923c3d1dd6f8d166edca2a',
    messagingSenderId: '427595722527',
    projectId: 'cofretrip',
    authDomain: 'cofretrip.firebaseapp.com',
    storageBucket: 'cofretrip.firebasestorage.app',
    measurementId: 'G-EE92XQNM1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPAvYjtt08fB1y4hM-eD40PF7Obej8fYA',
    appId: '1:427595722527:android:85da690f3280ec76edca2a',
    messagingSenderId: '427595722527',
    projectId: 'cofretrip',
    storageBucket: 'cofretrip.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX-Un3tHUrGvSBC6o6wDlesHRhABLyQP0',
    appId: '1:427595722527:ios:8418118e21a9f74bedca2a',
    messagingSenderId: '427595722527',
    projectId: 'cofretrip',
    storageBucket: 'cofretrip.firebasestorage.app',
    iosBundleId: 'com.example.travelbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX-Un3tHUrGvSBC6o6wDlesHRhABLyQP0',
    appId: '1:427595722527:ios:8418118e21a9f74bedca2a',
    messagingSenderId: '427595722527',
    projectId: 'cofretrip',
    storageBucket: 'cofretrip.firebasestorage.app',
    iosBundleId: 'com.example.travelbox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASgcpUqHrlqxnPCOcCdDuRhi-6xXMtroA',
    appId: '1:427595722527:web:836e3cced34306dbedca2a',
    messagingSenderId: '427595722527',
    projectId: 'cofretrip',
    authDomain: 'cofretrip.firebaseapp.com',
    storageBucket: 'cofretrip.firebasestorage.app',
    measurementId: 'G-JC0GCBCF7W',
  );

}